title: İhracat Notlarım
description: Timur Berk'in ihracat notları
show_excerpts: true


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"

  
