title: İhracat Notlarım
description: Timur Berk'in ihracat notları
author: Timur Berk
email: timurberk.com@gmail.com


# social links
twitter_username: timurberk_com
github_username:  timurberk
facebook_username: timurberk
flickr_username: timur
instagram_username: timurberk_com
linkedin_username: timurberk
rss: rss
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# dribbble_username: jekyll

#mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

header_pages:
  - about.md
#  - portfolio.md

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"

show_excerpts: true

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
